import type { Channel, CaseStatus, ContentSource, EvidenceType, ResultType, VerdictType, WitnessRole, ReactionType } from "./domain";

// ── 购物案类型 ──
export type ShoppingCase = {
  caseId: string;
  caseNumber: string;
  title: string;
  caseReason: string;
  statement: string;
  evidence: { type: EvidenceType; text: string }[];
  itemName: string;
  itemEmoji: string;
  priceCents: number;
  category: string;
  mood: string;
  user: string;
  userEmoji: string;
  channel: Channel;
  caseStatus: CaseStatus;
  contentSource: ContentSource;
  isDemo: boolean;
  isAnonymous?: boolean;
  createdAt: string;
  wait: string;
  tint: string;
  voteCounts: Record<ReactionType, number>;
  majorityVerdict?: VerdictType;
  commentCount: number;
  hasResult: boolean;
  resultType?: ResultType;
  hasFollowUp?: boolean;
  plotTwist?: string;
  bestTestimony?: { role: WitnessRole; author: string; emoji: string; content: string };
  sponsorName?: string;
  sponsorDisclosure?: string;
};

// ── 演示证词 ──
export type DemoTestimony = {
  id: string;
  caseId: string;
  role: WitnessRole;
  author: string;
  emoji: string;
  content: string;
  parentId?: string;
  createdAt: string;
};

// ── 演示案件数据 ──
export const demoCases: ShoppingCase[] = [
  {
    caseId: "dc1",
    caseNumber: "DD-2026-0826",
    title: "《关于我试图用买东西改变人生的申请》",
    caseReason: "想用智能水杯养成喝水习惯",
    statement: "普通杯子不会提醒我喝水，所以我一直不喝水。买了这个智能杯，我应该就能成为健康的人。",
    evidence: [
      { type: "HAS_SIMILAR_ITEM", text: "家里已有 7 个杯子" },
      { type: "NEW_DESIRE", text: "购物欲产生于 43 分钟前" },
      { type: "BUDGET_TIGHT", text: "本月预算有点紧" },
      { type: "LIMITED_PROMOTION", text: "促销还有 2 小时结束" },
    ],
    itemName: "智能水杯",
    itemEmoji: "🥤",
    priceCents: 79900,
    category: "数码",
    mood: "想改变生活习惯",
    user: "小满",
    userEmoji: "🌸",
    channel: "HOT_CASES",
    caseStatus: "JURY_VOTING",
    contentSource: "USER",
    isDemo: true,
    createdAt: "今天 10:24",
    wait: "刚提交",
    tint: "bg-[var(--blue-soft)]",
    voteCounts: { WORTH_IT: 8, WAIT: 24, RUN_AWAY: 12, SAME_DESIRE: 5, FOLLOW_UP: 10, SAVE: 6 },
    majorityVerdict: "COOLING_RECOMMENDED",
    commentCount: 18,
    hasResult: false,
    bestTestimony: { role: "EVIDENCE_PROVIDER", author: "栗子", emoji: "🌰", content: "姐妹，你缺的可能不是杯子，是接水。" },
  },
  {
    caseId: "dc2",
    caseNumber: "DD-2026-0715",
    title: "《只要买下它，我就会开始运动》",
    caseReason: "相信买了跑步机就会开始跑步",
    statement: "每次路过健身房都觉得浪费钱，如果家里有跑步机，我就没有借口了吧。而且这个颜色和客厅很配。",
    evidence: [
      { type: "HAS_SIMILAR_ITEM", text: "家里有瑜伽垫（已用来垫桌脚）" },
      { type: "NEW_DESIRE", text: "购物欲产生于昨晚刷短视频" },
      { type: "BUDGET_CONSIDER", text: "本月预算需要稍微考虑" },
    ],
    itemName: "家用跑步机",
    itemEmoji: "🏃",
    priceCents: 329900,
    category: "运动",
    mood: "想改变生活习惯",
    user: "晚风",
    userEmoji: "🍃",
    channel: "NEED_JURY",
    caseStatus: "JURY_VOTING",
    contentSource: "USER",
    isDemo: true,
    createdAt: "今天 08:15",
    wait: "等陪审团意见",
    tint: "bg-[var(--sage-soft)]",
    voteCounts: { WORTH_IT: 3, WAIT: 15, RUN_AWAY: 22, SAME_DESIRE: 2, FOLLOW_UP: 8, SAVE: 1 },
    majorityVerdict: "WALLET_PROTECTED",
    commentCount: 25,
    hasResult: false,
  },
  {
    caseId: "dc3",
    caseNumber: "DD-2026-0601",
    title: "《这不是冲动，是限时优惠先动的手》",
    caseReason: "限时折扣太诱人",
    statement: "原价 1299 的降噪耳机降到 899，这个折扣不买等于亏钱。而且每天地铁通勤 1.5 小时，真的很需要一个安静的角落。",
    evidence: [
      { type: "LIMITED_PROMOTION", text: "限时优惠还剩 6 小时" },
      { type: "LONG_CONSIDERATION", text: "已经关注了两周" },
      { type: "BUDGET_COMFORTABLE", text: "本月预算比较宽松" },
    ],
    itemName: "头戴式降噪耳机",
    itemEmoji: "🎧",
    priceCents: 89900,
    category: "数码",
    mood: "被限时优惠击中",
    user: "阿鹿",
    userEmoji: "🦌",
    channel: "COOLING_SENTENCE",
    caseStatus: "COOLING",
    contentSource: "USER",
    isDemo: true,
    createdAt: "昨天 21:10",
    wait: "钱包保护期 · 还剩 18 小时",
    tint: "bg-[var(--lemon-soft)]",
    voteCounts: { WORTH_IT: 32, WAIT: 18, RUN_AWAY: 8, SAME_DESIRE: 14, FOLLOW_UP: 6, SAVE: 10 },
    majorityVerdict: "APPROVED_BY_JURY",
    commentCount: 31,
    hasResult: false,
    bestTestimony: { role: "SAME_ITEM_OWNER", author: "桃子汽水", emoji: "🍑", content: "同款用了一年了，通勤幸福感直线上升，每天那个 30 分钟是属于自己的。" },
  },
  {
    caseId: "dc4",
    caseNumber: "DD-2026-0520",
    title: "《买了不一定快乐，不买今晚肯定惦记》",
    caseReason: "纠结一晚上了",
    statement: "这个香薰蜡烛套装看起来太治愈了，睡前点一会儿整个房间都会变温柔。但又觉得上次买的还没拆……",
    evidence: [
      { type: "HAS_SIMILAR_ITEM", text: "家里有 3 个未拆封香薰" },
      { type: "BUDGET_COMFORTABLE", text: "本月预算比较宽松" },
    ],
    itemName: "香薰蜡烛套装",
    itemEmoji: "🕯️",
    priceCents: 12900,
    category: "香薰",
    mood: "想让生活更温柔",
    user: "晚风",
    userEmoji: "🍃",
    channel: "GIVEN_UP",
    caseStatus: "CLOSED",
    contentSource: "USER",
    isDemo: true,
    createdAt: "3 天前",
    wait: "已结案",
    tint: "bg-[var(--sage-soft)]",
    voteCounts: { WORTH_IT: 6, WAIT: 20, RUN_AWAY: 15, SAME_DESIRE: 3, FOLLOW_UP: 4, SAVE: 2 },
    majorityVerdict: "COOLING_RECOMMENDED",
    commentCount: 12,
    hasResult: true,
    resultType: "GIVEN_UP",
    hasFollowUp: true,
    plotTwist: "COOLING_WORKED",
    bestTestimony: { role: "COOLING_ADVISER", author: "栗子", emoji: "🌰", content: "建议先点完家里那三个再考虑新的，亲测囤货的香味会变淡。" },
  },
  {
    caseId: "dc5",
    caseNumber: "DD-2026-0488",
    title: "《我的闺蜜劝我别买，所以申请社会评议》",
    caseReason: "闺蜜劝不住，请网友帮忙",
    statement: "这个降噪耳机闺蜜说家里有了别买，但这个牌子不一样！降噪效果完全不同！而且颜色也不一样！",
    evidence: [
      { type: "HAS_SIMILAR_ITEM", text: "家里有一副普通耳机" },
      { type: "NEW_DESIRE", text: "购物欲产生于 2 小时前" },
      { type: "BUDGET_TIGHT", text: "本月预算有点紧" },
    ],
    itemName: "降噪耳机",
    itemEmoji: "🎧",
    priceCents: 189900,
    category: "数码",
    mood: "被别人种草了",
    user: "阿鹿",
    userEmoji: "🦌",
    channel: "PLOT_TWIST",
    caseStatus: "CLOSED",
    contentSource: "USER",
    isDemo: true,
    createdAt: "一周前",
    wait: "已结案",
    tint: "bg-[var(--orange-soft)]",
    voteCounts: { WORTH_IT: 5, WAIT: 12, RUN_AWAY: 28, SAME_DESIRE: 8, FOLLOW_UP: 5, SAVE: 3 },
    majorityVerdict: "WALLET_PROTECTED",
    commentCount: 35,
    hasResult: true,
    resultType: "PURCHASED_LOVED",
    hasFollowUp: true,
    plotTwist: "JURY_WRONG_LOVED",
    bestTestimony: { role: "PURCHASED_USER", author: "小满", emoji: "🌸", content: "同款用了一周，通勤幸福感直线上升！每天那个安静的 30 分钟就是属于自己的时间。" },
  },
  {
    caseId: "dc6",
    caseNumber: "DD-2026-0420",
    title: "《如果买完会吃灰，那也是高级的灰》",
    caseReason: "想买空气炸锅",
    statement: "看博主做了一万个空气炸锅食谱，感觉自己也会变成厨艺达人。而且这个容量特别适合一人食。",
    evidence: [
      { type: "NEW_DESIRE", text: "购物欲产生于刷了一晚食谱" },
      { type: "BUDGET_CONSIDER", text: "本月预算需要稍微考虑" },
    ],
    itemName: "空气炸锅",
    itemEmoji: "🍳",
    priceCents: 29900,
    category: "家居",
    mood: "想成为更好的自己",
    user: "栗子",
    userEmoji: "🌰",
    channel: "PLOT_TWIST",
    caseStatus: "CLOSED",
    contentSource: "USER",
    isDemo: true,
    createdAt: "两周前",
    wait: "已结案",
    tint: "bg-[var(--orange-soft)]",
    voteCounts: { WORTH_IT: 18, WAIT: 8, RUN_AWAY: 10, SAME_DESIRE: 4, FOLLOW_UP: 3, SAVE: 2 },
    majorityVerdict: "APPROVED_BY_JURY",
    commentCount: 22,
    hasResult: true,
    resultType: "PURCHASED_REGRETTED",
    hasFollowUp: true,
    plotTwist: "JURY_WRONG_REGRETTED",
    bestTestimony: { role: "PURCHASED_USER", author: "桃子汽水", emoji: "🍑", content: "用了一次之后开始积灰，清洗太麻烦了，简直是当代最鸡肋厨房电器。" },
  },
  {
    caseId: "dc7",
    caseNumber: "DD-2026-0399",
    title: "《已有八个，但这个颜色确实没有》",
    caseReason: "颜色不一样就是不一样",
    statement: "我知道我已经有八个包包了，但这个焦糖色和秋天的氛围感绝配，其他颜色的包都给不了这种温暖的感觉。",
    evidence: [
      { type: "HAS_SIMILAR_ITEM", text: "家里已有 8 个包" },
      { type: "BUDGET_COMFORTABLE", text: "本月预算比较宽松" },
    ],
    itemName: "焦糖色通勤包",
    itemEmoji: "👜",
    priceCents: 45900,
    category: "服饰",
    mood: "被颜色击中",
    user: "桃子汽水",
    userEmoji: "🍑",
    channel: "CLOSED",
    caseStatus: "CLOSED",
    contentSource: "USER",
    isDemo: true,
    createdAt: "一个月前",
    wait: "已结案",
    tint: "bg-[#f3e9df]",
    voteCounts: { WORTH_IT: 15, WAIT: 22, RUN_AWAY: 10, SAME_DESIRE: 18, FOLLOW_UP: 2, SAVE: 8 },
    majorityVerdict: "COOLING_RECOMMENDED",
    commentCount: 28,
    hasResult: true,
    resultType: "BOUGHT_ALTERNATIVE",
    hasFollowUp: true,
    plotTwist: "ALTERNATIVE_WON",
    bestTestimony: { role: "ALTERNATIVE_SCOUT", author: "小满", emoji: "🌸", content: "推荐一个平替款，颜色几乎一模一样，价格只要三分之一，用了两个月质感依然很好！" },
  },
  {
    caseId: "dc8",
    caseNumber: "DD-2026-0355",
    title: "品牌送审 · 美容仪真实效果评估",
    caseReason: "品牌方提交产品供社区评估",
    statement: "品牌主张：这台美容仪每天使用十分钟，可以减少去美容院的频率。申请陪审团评估产品主张是否靠谱。",
    evidence: [
      { type: "CUSTOM", text: "品牌提供使用数据" },
      { type: "CUSTOM", text: "已提供第三方检测报告" },
    ],
    itemName: "家用美容仪",
    itemEmoji: "💆",
    priceCents: 199900,
    category: "美妆",
    mood: "品牌送审",
    user: "美境美研所",
    userEmoji: "🏢",
    channel: "HOT_CASES",
    caseStatus: "JURY_VOTING",
    contentSource: "SPONSORED",
    isDemo: true,
    isAnonymous: false,
    createdAt: "今天 09:00",
    wait: "品牌送审中",
    tint: "bg-[var(--lemon-soft)]",
    voteCounts: { WORTH_IT: 4, WAIT: 12, RUN_AWAY: 6, SAME_DESIRE: 3, FOLLOW_UP: 8, SAVE: 5 },
    majorityVerdict: "JURY_DIVIDED",
    commentCount: 15,
    hasResult: false,
    sponsorName: "美境美研所",
    sponsorDisclosure: "本案件为品牌送审内容，平台可能获得商业收益。品牌内容不影响自然案件排序和风险分析。",
  },
  {
    caseId: "dc9",
    caseNumber: "DD-2026-0312",
    title: "《这是刚需，只是这个刚需有一点贵》",
    caseReason: "电脑太重了每天背着肩膀疼",
    statement: "现在这台电脑 2.3kg，每天背着通勤肩膀都要断了。看中一台 1.1kg 的轻薄本，就是价格有点超预算，但确实是刚需……",
    evidence: [
      { type: "NECESSITY", text: "属于工作刚需" },
      { type: "LONG_CONSIDERATION", text: "已经考虑了三周" },
      { type: "BUDGET_TIGHT", text: "本月预算有点紧" },
      { type: "PLANNED_PURCHASE", text: "属于计划内消费" },
    ],
    itemName: "轻便办公本",
    itemEmoji: "💻",
    priceCents: 599900,
    category: "数码",
    mood: "确实有实际需要",
    user: "晚风",
    userEmoji: "🍃",
    channel: "NEED_JURY",
    caseStatus: "JURY_VOTING",
    contentSource: "USER",
    isDemo: true,
    createdAt: "今天 14:30",
    wait: "急求参谋",
    tint: "bg-[var(--blue-soft)]",
    voteCounts: { WORTH_IT: 28, WAIT: 5, RUN_AWAY: 3, SAME_DESIRE: 2, FOLLOW_UP: 4, SAVE: 6 },
    majorityVerdict: "APPROVED_BY_JURY",
    commentCount: 19,
    hasResult: false,
    bestTestimony: { role: "DEFENSE", author: "阿鹿", emoji: "🦌", content: "作为每天背电脑通勤的人，1.1kg 和 2.3kg 的差别真的巨大，肩膀不再疼这件事对生活质量影响很大。" },
  },
  {
    caseId: "dc10",
    caseNumber: "DD-2026-0288",
    title: "《工作已经很苦了，申请给自己一点甜》",
    caseReason: "想奖励辛苦工作的自己",
    statement: "连续加班两周了，路过柜台看到这个巧克力礼盒，感觉就是生活里的一点甜。虽然有点贵，但情绪价值也是价值吧？",
    evidence: [
      { type: "NEW_DESIRE", text: "路过被吸引" },
      { type: "BUDGET_COMFORTABLE", text: "本月预算比较宽松" },
    ],
    itemName: "限量手工巧克力礼盒",
    itemEmoji: "🍫",
    priceCents: 19800,
    category: "食品",
    mood: "想奖励自己",
    user: "栗子",
    userEmoji: "🌰",
    channel: "CLOSED",
    caseStatus: "CLOSED",
    contentSource: "USER",
    isDemo: true,
    createdAt: "两周前",
    wait: "已结案",
    tint: "bg-[#f3e9df]",
    voteCounts: { WORTH_IT: 35, WAIT: 4, RUN_AWAY: 2, SAME_DESIRE: 8, FOLLOW_UP: 1, SAVE: 3 },
    majorityVerdict: "APPROVED_BY_JURY",
    commentCount: 14,
    hasResult: true,
    resultType: "PURCHASED_LOVED",
    hasFollowUp: false,
    bestTestimony: { role: "PURCHASED_USER", author: "桃子汽水", emoji: "🍑", content: "买了同款！真的是很治愈的小确幸，每次吃一颗都觉得很幸福。" },
  },
  {
    caseId: "dc11",
    caseNumber: "DD-2026-0201",
    title: "《虽然用不到，但它真的很适合放在家里》",
    caseReason: "看中一个拍立得",
    statement: "看大家做旅行手账好心动，但家里已经有一个拍立得相机积灰了……不过这个新款支持蓝牙连接手机打印，功能完全不一样！",
    evidence: [
      { type: "HAS_SIMILAR_ITEM", text: "家里有一个旧款拍立得" },
      { type: "NEW_DESIRE", text: "购物欲产生于看了一晚手账视频" },
      { type: "BUDGET_CONSIDER", text: "本月预算需要稍微考虑" },
    ],
    itemName: "口袋照片打印机",
    itemEmoji: "📷",
    priceCents: 69900,
    category: "数码",
    mood: "被别人种草了",
    user: "小满",
    userEmoji: "🌸",
    channel: "GIVEN_UP",
    caseStatus: "CLOSED",
    contentSource: "USER",
    isDemo: true,
    createdAt: "一个月前",
    wait: "已结案",
    tint: "bg-[var(--blue-soft)]",
    voteCounts: { WORTH_IT: 8, WAIT: 15, RUN_AWAY: 12, SAME_DESIRE: 6, FOLLOW_UP: 5, SAVE: 4 },
    majorityVerdict: "COOLING_RECOMMENDED",
    commentCount: 20,
    hasResult: true,
    resultType: "GIVEN_UP",
    hasFollowUp: true,
    plotTwist: "COOLING_WORKED",
    bestTestimony: { role: "SAME_ITEM_OWNER", author: "晚风", emoji: "🍃", content: "同款买了三个月，用了五次。相纸太贵了，建议先用手机修图 app 模拟一下打印的感觉。" },
  },
  {
    caseId: "dc12",
    caseNumber: "DD-2026-0155",
    title: "《申请用下个月的钱安慰今天的自己》",
    caseReason: "看中一条碎花裙",
    statement: "下周朋友生日聚会，衣柜里没有适合夏天的浅色裙子。虽然预算不多了，但买下它心情会好一整天吧。",
    evidence: [
      { type: "BUDGET_TIGHT", text: "本月预算有点紧" },
      { type: "NEW_DESIRE", text: "购物欲产生于刷到穿搭博主" },
    ],
    itemName: "春天第一条碎花裙",
    itemEmoji: "👗",
    priceCents: 34900,
    category: "服饰",
    mood: "被别人种草了",
    user: "小满",
    userEmoji: "🌸",
    channel: "COOLING_SENTENCE",
    caseStatus: "COOLING",
    contentSource: "USER",
    isDemo: true,
    createdAt: "昨天 15:20",
    wait: "钱包保护期 · 还剩 22 小时",
    tint: "bg-[var(--lemon-soft)]",
    voteCounts: { WORTH_IT: 12, WAIT: 16, RUN_AWAY: 4, SAME_DESIRE: 20, FOLLOW_UP: 3, SAVE: 7 },
    majorityVerdict: "COOLING_RECOMMENDED",
    commentCount: 10,
    hasResult: false,
  },
];

// ── 演示证词 ──
export const demoTestimonies: DemoTestimony[] = [
  { id: "t1", caseId: "dc1", role: "EVIDENCE_PROVIDER", author: "栗子", emoji: "🌰", content: "姐妹，你缺的可能不是杯子，是接水。", createdAt: "1 小时前" },
  { id: "t2", caseId: "dc1", role: "SAME_ITEM_OWNER", author: "阿鹿", emoji: "🦌", content: "我买了同款，用了一周就开始积灰。提醒功能确实有用，但三天后我就关了。", createdAt: "45 分钟前" },
  { id: "t3", caseId: "dc1", role: "DEFENSE", author: "晚风", emoji: "🍃", content: "说实话智能杯确实比普通杯更能培养习惯，灯光提醒比手机通知管用。", createdAt: "30 分钟前" },
  { id: "t4", caseId: "dc2", role: "COOLING_ADVISER", author: "桃子汽水", emoji: "🍑", content: "建议先去楼下公园跑七天，如果七天后还想买跑步机，再考虑。", createdAt: "2 小时前" },
  { id: "t5", caseId: "dc2", role: "EVIDENCE_PROVIDER", author: "栗子", emoji: "🌰", content: "关键证据：当事人瑜伽垫已用来垫桌脚。", createdAt: "1 小时前" },
  { id: "t6", caseId: "dc3", role: "PURCHASED_USER", author: "小满", emoji: "🌸", content: "同款通勤用了一年，每天那个安静的 30 分钟是属于自己的时间。", createdAt: "3 小时前" },
  { id: "t7", caseId: "dc3", role: "ALTERNATIVE_SCOUT", author: "阿鹿", emoji: "🦌", content: "推荐试试 200 出头的入耳式降噪，效果差距不大但价格友好很多。", createdAt: "2 小时前" },
  { id: "t8", caseId: "dc5", role: "PURCHASED_USER", author: "小满", emoji: "🌸", content: "同款用了一周，通勤幸福感直线上升！每天那个安静的 30 分钟就是属于自己的时间。", createdAt: "5 天前" },
  { id: "t9", caseId: "dc6", role: "PURCHASED_USER", author: "桃子汽水", emoji: "🍑", content: "用了一次之后开始积灰，清洗太麻烦了，简直是当代最鸡肋厨房电器。", createdAt: "一周前" },
  { id: "t10", caseId: "dc7", role: "ALTERNATIVE_SCOUT", author: "小满", emoji: "🌸", content: "推荐一个平替款，颜色几乎一模一样，价格只要三分之一，用了两个月质感依然很好！", createdAt: "两周前" },
];

// ── 今日热案数据 ──
export const todayHotCases = [
  { caseId: "dc1", reason: "今日最离谱案由", label: "智能水杯改变人生" },
  { caseId: "dc2", reason: "陪审团吵得最凶", label: "跑步机 vs 楼下公园" },
  { caseId: "dc5", reason: "最强反转案件", label: "陪审团劝别买 → 买后真香" },
  { caseId: "dc8", reason: "品牌送审", label: "美容仪真实效果" },
];
