create extension if not exists pgcrypto;
create type public.relationship_status as enum ('PENDING','ACTIVE','ENDED');
create type public.request_status as enum ('DRAFT','PENDING_APPROVAL','NEED_MORE_INFO','APPROVED','REJECTED','COOLING_OFF','READY_TO_BUY','PURCHASED','GIVEN_UP','CANCELLED','EXPIRED');
create type public.approval_decision as enum ('APPROVE','REJECT','WAIT','MORE_INFO');

create table public.profiles(id uuid primary key references auth.users on delete cascade,nickname text not null default '新朋友',avatar_url text,created_at timestamptz not null default now());
create table public.supervision_relationships(id uuid primary key default gen_random_uuid(),inviter_id uuid not null references public.profiles,invitee_id uuid references public.profiles,invite_code text not null unique default upper(substr(encode(gen_random_bytes(8),'hex'),1,8)),relationship_name text not null default '省钱搭子',status public.relationship_status not null default 'PENDING',permissions jsonb not null default '{"share_history":true,"share_budget_snapshot":true}',expires_at timestamptz not null default now()+interval '7 days',ended_at timestamptz,created_at timestamptz not null default now(),check(inviter_id<>invitee_id));
create unique index one_active_relationship_per_pair on public.supervision_relationships(least(inviter_id,invitee_id),greatest(inviter_id,invitee_id)) where status='ACTIVE';
create table public.monthly_budgets(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles on delete cascade,living_allowance bigint not null check(living_allowance>=0),fixed_expenses bigint not null check(fixed_expenses>=0),saving_goal bigint not null check(saving_goal>=0),discretionary_budget bigint generated always as (living_allowance-fixed_expenses-saving_goal) stored,spent_amount bigint not null default 0 check(spent_amount>=0),remaining_amount bigint generated always as (living_allowance-fixed_expenses-saving_goal-spent_amount) stored,safe_balance bigint not null default 0 check(safe_balance>=0),period_start date not null,period_end date not null,created_at timestamptz not null default now(),unique(user_id,period_start),check(living_allowance>=fixed_expenses+saving_goal),check(period_end>=period_start));
create table public.purchase_requests(id uuid primary key default gen_random_uuid(),applicant_id uuid not null references public.profiles,reviewer_id uuid not null references public.profiles,item_name text not null,item_price bigint not null check(item_price>0),category text not null,image_url text,product_url text,purchase_reason text not null,impact_if_not_purchased text,has_similar_item boolean not null default false,desired_hours integer not null default 0,limited_promotion boolean not null default false,planned_purchase boolean not null default false,necessity boolean not null default false,budget_snapshot bigint not null,remaining_budget_snapshot bigint not null,remaining_after_purchase bigint not null,risk_score smallint not null check(risk_score between 0 and 100),risk_level text not null,cooling_period_hours integer not null default 24,cooling_ends_at timestamptz,status public.request_status not null default 'DRAFT',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(applicant_id<>reviewer_id));
create index requests_applicant_idx on public.purchase_requests(applicant_id,created_at desc);create index requests_reviewer_idx on public.purchase_requests(reviewer_id,status);
create table public.approvals(id uuid primary key default gen_random_uuid(),purchase_request_id uuid not null references public.purchase_requests on delete cascade,reviewer_id uuid not null references public.profiles,decision public.approval_decision not null,comment text,suggested_wait_hours integer,recommended_alternative text,created_at timestamptz not null default now(),unique(purchase_request_id));
create table public.request_status_logs(id bigint generated always as identity primary key,purchase_request_id uuid not null references public.purchase_requests on delete cascade,from_status public.request_status,to_status public.request_status not null,operator_id uuid not null references public.profiles,note text,created_at timestamptz not null default now());
create table public.purchase_results(id uuid primary key default gen_random_uuid(),purchase_request_id uuid not null unique references public.purchase_requests on delete cascade,result text not null check(result in('PURCHASED','GIVEN_UP','DELAYED','REPLACED')),actual_price bigint check(actual_price>=0),purchased_at timestamptz,reason_for_giving_up text,saved_amount bigint not null default 0,created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles on delete cascade,type text not null,title text not null,content text not null,related_request_id uuid references public.purchase_requests on delete cascade,is_read boolean not null default false,created_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,nickname) values(new.id,coalesce(new.raw_user_meta_data->>'nickname','新朋友'));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.log_request_status() returns trigger language plpgsql security definer set search_path=public as $$begin if old.status is distinct from new.status then insert into request_status_logs(purchase_request_id,from_status,to_status,operator_id) values(new.id,old.status,new.status,auth.uid());end if;new.updated_at=now();return new;end$$;
create trigger purchase_request_status_changed before update on public.purchase_requests for each row execute function public.log_request_status();

create or replace function public.confirm_purchase(p_request_id uuid,p_actual_price bigint) returns void language plpgsql security definer set search_path=public as $$declare r purchase_requests;b monthly_budgets;begin select * into r from purchase_requests where id=p_request_id and applicant_id=auth.uid() for update;if r.id is null or r.status<>'READY_TO_BUY' then raise exception 'invalid request state';end if;select * into b from monthly_budgets where user_id=auth.uid() and current_date between period_start and period_end for update;if b.id is null then raise exception 'budget not found';end if;if exists(select 1 from purchase_results where purchase_request_id=p_request_id) then raise exception 'already finalized';end if;insert into purchase_results(purchase_request_id,result,actual_price,purchased_at)values(p_request_id,'PURCHASED',p_actual_price,now());update monthly_budgets set spent_amount=spent_amount+p_actual_price where id=b.id;update purchase_requests set status='PURCHASED' where id=r.id;end$$;

alter table profiles enable row level security;alter table supervision_relationships enable row level security;alter table monthly_budgets enable row level security;alter table purchase_requests enable row level security;alter table approvals enable row level security;alter table request_status_logs enable row level security;alter table purchase_results enable row level security;alter table notifications enable row level security;
create policy "profile self or active peer read" on profiles for select using(id=auth.uid() or exists(select 1 from supervision_relationships s where s.status='ACTIVE' and ((s.inviter_id=auth.uid() and s.invitee_id=id)or(s.invitee_id=auth.uid() and s.inviter_id=id))));create policy "profile self update" on profiles for update using(id=auth.uid());
create policy "relationship members read" on supervision_relationships for select using(auth.uid() in(inviter_id,invitee_id));create policy "create own invite" on supervision_relationships for insert with check(inviter_id=auth.uid());create policy "members update relationship" on supervision_relationships for update using(auth.uid() in(inviter_id,invitee_id));
create policy "budget owner all" on monthly_budgets for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "request parties read" on purchase_requests for select using(auth.uid() in(applicant_id,reviewer_id));create policy "applicant creates" on purchase_requests for insert with check(applicant_id=auth.uid() and exists(select 1 from supervision_relationships s where s.status='ACTIVE' and auth.uid() in(s.inviter_id,s.invitee_id) and reviewer_id in(s.inviter_id,s.invitee_id)));create policy "request parties update" on purchase_requests for update using(auth.uid() in(applicant_id,reviewer_id));
create policy "approval parties read" on approvals for select using(exists(select 1 from purchase_requests r where r.id=purchase_request_id and auth.uid() in(r.applicant_id,r.reviewer_id)));create policy "assigned reviewer approves" on approvals for insert with check(reviewer_id=auth.uid() and exists(select 1 from purchase_requests r where r.id=purchase_request_id and r.reviewer_id=auth.uid() and r.status='PENDING_APPROVAL'));
create policy "request parties read logs" on request_status_logs for select using(exists(select 1 from purchase_requests r where r.id=purchase_request_id and auth.uid() in(r.applicant_id,r.reviewer_id)));create policy "applicant reads results" on purchase_results for select using(exists(select 1 from purchase_requests r where r.id=purchase_request_id and r.applicant_id=auth.uid()));create policy "own notifications" on notifications for select using(user_id=auth.uid());create policy "update own notifications" on notifications for update using(user_id=auth.uid());
grant execute on function public.confirm_purchase(uuid,bigint) to authenticated;
